#include "arduino_secrets.h"
/*
  Sketch generated by the Arduino IoT Cloud Thing "LoraTest"
  https://create.arduino.cc/cloud/things/1266bec0-da42-4a33-96a5-9526426f1510

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float hum;
  float temp;
  int test;
  bool led;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include "DHT.h"

DHT dht(3, DHT11);

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  dht.begin();
  hum = dht.readHumidity();
  temp = dht.readTemperature();

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(4);
  ArduinoCloud.printDebugInfo();
}

unsigned long last_time = 0;

void loop() {
  

  unsigned long new_time = millis();
  if (new_time - 10000 > last_time) {
    last_time = new_time;
    hum = dht.readHumidity();
    temp = dht.readTemperature();
    ArduinoCloud.update();
    ArduinoCloud.printDebugInfo();

    Serial.print("Luftfeuchtigkeit: ");
    Serial.print(hum);
    Serial.print(" %\t");
    Serial.print("Temperatur: ");
    Serial.print(temp);
    Serial.println(" Grad Celsius");
    test = test + 1;
    Serial.print("counter is now: ");
    Serial.println(test);
  }

}


/*
  Since Led is READ_WRITE variable, onLedChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLedChange()  {
  if (led) {
    digitalWrite(LED_BUILTIN, HIGH);  //turn on GREEN
  } else {
    digitalWrite(LED_BUILTIN, LOW);  //turn off GREEN
  }
}



















