// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char APPEUI[]   = SECRET_APP_EUI;
const char APPKEY[]   = SECRET_APP_KEY;

void onLedChange();

float hum;
float temp;
int test;
bool led;

void initProperties(){
  ArduinoCloud.addProperty(hum, 4, READ, 60 * SECONDS, NULL);
  ArduinoCloud.addProperty(temp, 3, READ, 60 * SECONDS, NULL);
  ArduinoCloud.addProperty(test, 1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(led, 2, READWRITE, ON_CHANGE, onLedChange);

}

LoRaConnectionHandler ArduinoIoTPreferredConnection(APPEUI, APPKEY, _lora_band::EU868);
