#include "arduino_secrets.h"
/*
  Sketch generated by the Arduino IoT Cloud Thing "LoraTest"
  https://create.arduino.cc/cloud/things/1266bec0-da42-4a33-96a5-9526426f1510

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float hum;
  float temp;
  int test;
  bool led;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/
#include <Adafruit_SleepyDog.h>     //Needed to initiate reboots by the SAMD WatchDog 
#include "thingProperties.h"
#include "DHT.h"image.png

DHT dht(3, DHT11);

void setup() {
  dht.begin();
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection, false);  // false - do not use AIoTC watchdog - will use Adafruit SleepyDog instead

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(4);
  ArduinoCloud.printDebugInfo();
  
  // DHT11 needs a few seconds to return reliable measurements
  // in addition to the 1 second below in the loop for the
  // first measurement
  delay(2000);
}

// Timer for IoT Cloud Update
unsigned long previousMillisIOT = 0;
float intervalIOT = 1000;                      // IoT-Update interval = 1 seconds

// For the power management (Standby) 
// see https://create.arduino.cc/projecthub/andreas_waldherr/mkr-wan-1310-iot-operating-at-0-92ma-879793
unsigned long JustStarted_Timer = 42000;
int sleep_cycles = 52;
boolean sleep_now = false;

void loop() {
  
  unsigned long currentMillisIOT = millis();
  if (currentMillisIOT - previousMillisIOT >= intervalIOT) {
      previousMillisIOT = currentMillisIOT;
      
      // Send and get updates from the Arduino IoT Cloud
    hum = dht.readHumidity();
    temp = dht.readTemperature();
    ArduinoCloud.update();
    ArduinoCloud.printDebugInfo();
    Serial.print("Luftfeuchtigkeit: ");
    Serial.print(hum);
    Serial.print(" %\t");
    Serial.print("Temperatur: ");
    Serial.print(temp);
    Serial.println(" Grad Celsius");
    test = test + 1;
    Serial.print("counter is now: ");
    Serial.println(test);
      
  }
  
  // 42 seconds have passed after MKR startup
  if (millis() > JustStarted_Timer) {
    sleep_now = true;
    Serial.println("Will now sleep for 15 minutes");
  }
  
  // Go to STANDBY Mode for 52 times 
  if (sleep_now == true) {
    for (int i = 0; i < sleep_cycles; i++) {
      Serial.print("Deep sleep cycle ");
      Serial.println(i+1);
      Watchdog.sleep();                           // Enter the Standby Mode for 16,5 seconds (MKR WAN 1310 specific)
    }

    
    // Now restart the MKR
    int countdownMS = Watchdog.enable(100);      // WatchDog timeout in 0.1 seconds
    delay(countdownMS+1000);                     // Wait for 1.1 second!!!
    Watchdog.disable();                          // The WatchDog WILL time out and therefore restart the CPU
  }

}


/*
  Since Led is READ_WRITE variable, onLedChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLedChange()  {
  if (led) {
    digitalWrite(LED_BUILTIN, HIGH);  //turn on GREEN
  } else {
    digitalWrite(LED_BUILTIN, LOW);  //turn off GREEN
  }
}





















