// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char APPEUI[]   = SECRET_APP_EUI;
const char APPKEY[]   = SECRET_APP_KEY;

void onLedChange();

float hum;
float temp;
float volt;
bool led;

void initProperties(){
  ArduinoCloud.addProperty(hum, 4, READ, 15 * SECONDS, NULL);
  ArduinoCloud.addProperty(temp, 3, READ, 15 * SECONDS, NULL);
  ArduinoCloud.addProperty(volt, 5, READ, 15 * SECONDS, NULL);
  ArduinoCloud.addProperty(led, 2, READWRITE, ON_CHANGE, onLedChange);

}

LoRaConnectionHandler ArduinoIoTPreferredConnection(APPEUI, APPKEY, _lora_band::EU868);
